// <auto-generated />
using System;
using CityBreaks.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityBreaks.Web.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250606232553_AddSoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Brasília"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Osaka"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Shenzhen"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            Name = "Macau"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 4,
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 4,
                            Name = "Saint Petersburg"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("CountryName");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "BR",
                            CountryName = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "JP",
                            CountryName = "Japan"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "CN",
                            CountryName = "China"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "RU",
                            CountryName = "Russia"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Royal Tulip",
                            PricePerNight = 140.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Name = "Hilton Rio de Janeiro Copacabana",
                            PricePerNight = 250.00m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Name = "Aman Tokyo",
                            PricePerNight = 1720.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Imperial Hotel Ōsaka",
                            PricePerNight = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Name = "Futian Shangri-La",
                            PricePerNight = 180.00m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Name = "Artyzen Grand Lapa",
                            PricePerNight = 180.00m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Name = "Hilton Moscow Leningradskaya",
                            PricePerNight = 160.00m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 8,
                            Name = "Nevsky Royal Hotel",
                            PricePerNight = 150.00m
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
